apiVersion: v1
kind: Pod 
metadata:
  name: secret-pod 
  labels:
    topic: secrets
spec:
  volumes:
    - name: secret-vol
      secret: 
        secretName: mysecret 
  containers:
    - name: secret-pod
      image: nginx
      volumeMounts:
        - name: secret-vol
          mountPath: "/etc/hi"
          readOnly: true 