apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:php8.3-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: "172.29.147.94:3306"
        - name: WORDPRESS_DB_USER
          value: "hori"
        - name: WORDPRESS_DB_PASSWORD
          value: "123"
        - name: WORDPRESS_DB_NAME
          value: "hori"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: ClusterIP
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80